### ISSUE TITLE
Exceptions on running collector

### ISSUE THREAD

**Issue by avadhmr** [tabladrum/fortify-collector#2]
So I was able to build the collector but wasn't able to get it running due to these exceptions 
Any thoughts on what I am missing here?

2017-02-06 03:17:11,021 WARN  c.f.w.c.ClientAuthenticationInterceptor - Could not validate request: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired); nested exception is org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired)
2017-02-06 03:17:11,022 ERROR com.fortify.ws.client.ProjectClient - Exception sending request
org.springframework.ws.soap.security.wss4j.Wss4jSecurityValidationException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired); nested exception is org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired)
        at org.springframework.ws.soap.security.wss4j.Wss4jSecurityInterceptor.validateMessage(Wss4jSecurityInterceptor.java:580) ~[spring-ws-security-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.soap.security.AbstractWsSecurityInterceptor.handleResponse(AbstractWsSecurityInterceptor.java:235) ~[spring-ws-security-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.triggerHandleResponse(WebServiceTemplate.java:732) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:595) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:537) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:384) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:370) ~[spring-ws-core-2.0.5.RELEASE.jar!/:na]
        at com.fortify.ws.client.AbstractWSClient.sendRequest(AbstractWSClient.java:132) [wsclient-4.30.jar!/:na]
        at com.fortify.ws.client.AbstractWSClient.sendRequest(AbstractWSClient.java:113) [wsclient-4.30.jar!/:na]
        at com.fortify.ws.client.ProjectClient.getProjects(ProjectClient.java:32) [wsclient-4.30.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultFortifyClient.listProjectVersions(DefaultFortifyClient.java:78) [fortify-collector-1.0.jar!/:1.0]
        at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:83) [fortify-collector-1.0.jar!/:1.0]
        at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:27) [fortify-collector-1.0.jar!/:1.0]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:1.0]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired)
        at org.apache.ws.security.processor.TimestampProcessor.handleTimestamp(TimestampProcessor.java:88) ~[wss4j-1.5.8.jar!/:1.5.8]
        at org.apache.ws.security.processor.TimestampProcessor.handleToken(TimestampProcessor.java:60) ~[wss4j-1.5.8.jar!/:1.5.8]
        at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:326) ~[wss4j-1.5.8.jar!/:1.5.8]
        at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:243) ~[wss4j-1.5.8.jar!/:1.5.8]
        at org.springframework.ws.soap.security.wss4j.Wss4jSecurityInterceptor.validateMessage(Wss4jSecurityInterceptor.java:558) ~[spring-ws-security-2.0.5.RELEASE.jar!/:na]
        ... 23 common frames omitted
com.fortify.ws.client.FortifyWebServiceException: An internal error has occurred.
(org.springframework.ws.soap.security.wss4j.Wss4jSecurityValidationException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired); nested exception is org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired))
(IOException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired))
        at com.fortify.ws.client.AbstractWSClient.transformException(AbstractWSClient.java:239)
        at com.fortify.ws.client.AbstractWSClient.sendRequest(AbstractWSClient.java:142)
        at com.fortify.ws.client.AbstractWSClient.sendRequest(AbstractWSClient.java:113)
        at com.fortify.ws.client.ProjectClient.getProjects(ProjectClient.java:32)
        at com.capitalone.dashboard.collector.DefaultFortifyClient.listProjectVersions(DefaultFortifyClient.java:78)
        at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:83)
        at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:27)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.ws.soap.security.wss4j.Wss4jSecurityValidationException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired); nested exception is org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired)
        at org.springframework.ws.soap.security.wss4j.Wss4jSecurityInterceptor.validateMessage(Wss4jSecurityInterceptor.java:580)
        at org.springframework.ws.soap.security.AbstractWsSecurityInterceptor.handleResponse(AbstractWsSecurityInterceptor.java:235)
        at org.springframework.ws.client.core.WebServiceTemplate.triggerHandleResponse(WebServiceTemplate.java:732)
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:595)
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:537)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:384)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:370)
        at com.fortify.ws.client.AbstractWSClient.sendRequest(AbstractWSClient.java:132)
        ... 15 more

**Comment by avadhmr** [comment]
Ok So I figured out the above error was due to me using core 2.0.5 for building fortify..I used 2.0.0 instead and that exception was gone but I am getting a new one now which I think is due to the latest version of api
Any thoughts on how to fix this?

org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type com.capitalone.dashboard.model.CollectorType for value 'AgileTool'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.CollectorType.AgileTool
