### ISSUE TITLE
Exceptions on running the collector 

### ISSUE THREAD

**Issue by akillam-007** [tabladrum/fortify-collector#3]
I tried getting all the below jars in **version 16.10 instead of the versions 4.30 given below**: 
•	com.fortify:fortify-common:jar:4.30,
•	com.fortify:fortify-crypto:jar:1.0,
•	com.fortify:fortify-meta-api:jar:4.30,
•	com.fortify:fortify-meta-impl:jar:4.30,
•	com.fortify:fortify-public:jar:4.30,
•	com.sun.xml.wsit:xws-security:jar:1.3.1,
•	com.sun.xml.wsit:wsit-rt:jar:1.1,
•	com.fortify:wsclient:jar:4.30,
•	com.fortify:wsobject:jar:4.30,     

While trying to run with 16.10 version of the jars I am facing the below error . Is it the jar version dependent?

error : 
2018-07-03 18:58:00,063 INFO  o.s.c.s.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@15227cd3: startup date [Tue Jul 03 18:58:00 IST 2018]; root of context hierarchy
2018-07-03 18:58:00,064 INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [ws-client-config.xml]
2018-07-03 18:58:00,116 INFO  o.s.b.f.c.PropertyPlaceholderConfigurer - Loading properties file from class path resource [ws.client.properties]
2018-07-03 18:58:00,130 WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageFactory' defined in class path resource [ws-client-config.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ws.soap.axiom.AxiomSoapMessageFactory]: Constructor threw exception; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
2018-07-03 18:58:00,131 INFO  o.s.c.s.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@4e10fc91: startup date [Tue Jul 03 18:58:00 IST 2018]; root of context hierarchy
2018-07-03 18:58:00,131 INFO  o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [ws-client-config.xml]
2018-07-03 18:58:00,157 INFO  o.s.b.f.c.PropertyPlaceholderConfigurer - Loading properties file from class path resource [ws.client.properties]
2018-07-03 18:58:00,164 WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageFactory' defined in class path resource [ws-client-config.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ws.soap.axiom.AxiomSoapMessageFactory]: Constructor threw exception; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
2018-07-03 18:58:00,165 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageFactory' defined in class path resource [ws-client-config.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ws.soap.axiom.AxiomSoapMessageFactory]: Constructor threw exception; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.fortify.ws.core.ClientCore.<init>(ClientCore.java:57) ~[wsclient-16.10.jar:na]
	at com.capitalone.dashboard.collector.FortifyWSTemplate.<init>(FortifyWSTemplate.java:11) ~[classes/:na]
	at com.capitalone.dashboard.collector.DefaultFortifyClient.listProjectVersions(DefaultFortifyClient.java:73) ~[classes/:na]
	at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:83) ~[classes/:na]
	at com.capitalone.dashboard.collector.DefaultFortifyCollectorTask.collect(DefaultFortifyCollectorTask.java:1) ~[classes/:na]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ws.soap.axiom.AxiomSoapMessageFactory]: Constructor threw exception; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 27 common frames omitted
Caused by: javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:370) ~[na:1.8.0_172]
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:313) ~[na:1.8.0_172]
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:227) ~[na:1.8.0_172]
	at javax.xml.stream.XMLInputFactory.newInstance(XMLInputFactory.java:154) ~[na:1.8.0_172]
	at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createXmlInputFactory(AxiomSoapMessageFactory.java:331) ~[spring-ws-core-2.0.5.RELEASE.jar:na]
	at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.<init>(AxiomSoapMessageFactory.java:91) ~[spring-ws-core-2.0.5.RELEASE.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_172]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_172]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 29 common frames omitted
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:367) ~[na:1.8.0_172]
	... 39 common frames omitted
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Provider com.sun.xml.stream.ZephyrParserFactory not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[na:1.8.0_172]
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[na:1.8.0_172]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) ~[na:1.8.0_172]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_172]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_172]
	at javax.xml.stream.FactoryFinder$1.run(FactoryFinder.java:353) ~[na:1.8.0_172]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_172]
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:341) ~[na:1.8.0_172]
	... 39 common frames omitted

**Comment by arunmk108** [comment]
Hi Akillam, Is this issue fixed or still exists. If fixed, can you share the root cause? Iam also facing the same issue.
